#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 15, 2019 11:43:35 AM PKT  platform: Windows NT

import record_and_play

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

username = "Harry Potter"
password = "harry"


def login():
    print('login_support.login')
    if w.TEntry1.get() == username and w.TEntry2.get() == password:
        destroy_window()
        record_and_play.vp_start_gui()

    else:
        w.Label6.configure(text="Invalid Username or Password!")


def init(top, gui):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    login.vp_start_gui()
