#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 15, 2019 12:58:31 PM PKT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x347+413+107
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab46 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 21 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {AUDIO DIARY} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra62 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 235 -width 235 
    vTcl:DefineAlias "$top.fra62" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra62
    label $site_3_0.lab63 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Record Audio} 
    vTcl:DefineAlias "$site_3_0.lab63" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e1031e -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Record 
    vTcl:DefineAlias "$site_3_0.but64" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #008000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Stop 
    vTcl:DefineAlias "$site_3_0.but65" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {No Audio Recorded} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Save As} 
    vTcl:DefineAlias "$site_3_0.but82" "Button5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 10 -y 10 -width 214 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 37 -y 60 -width 157 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 37 -y 100 -width 157 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 63 -y 200 -width 104 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but82 \
        -in $site_3_0 -x 37 -y 150 -width 157 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr67 \
        -borderwidth 2 -relief groove -width 275 -height 175 
    vTcl:DefineAlias "$top.tFr67" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr67
    button $site_3_0.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Upload File} 
    vTcl:DefineAlias "$site_3_0.but73" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but74 \
        -activebackground #008000 -activeforeground #000000 \
        -background #008000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Play 
    vTcl:DefineAlias "$site_3_0.but74" "Button4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Play Audio} 
    vTcl:DefineAlias "$site_3_0.lab77" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Select File to Play} 
    vTcl:DefineAlias "$site_3_0.lab78" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {No File Selected} 
    vTcl:DefineAlias "$site_3_0.lab81" "Label5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but73 \
        -in $site_3_0 -x 30 -y 90 -width 117 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but74 \
        -in $site_3_0 -x 80 -y 130 -width 117 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 30 -y 10 -width 214 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 20 -y 50 -width 234 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 160 -y 90 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 10 -y 10 -width 578 -relwidth 0 -height 61 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra62 \
        -in $top -x 30 -y 70 -width 235 -relwidth 0 -height 235 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr67 \
        -in $top -x 290 -y 70 -width 275 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

